name: Build TWRP for LG v600tm

on:
  workflow_dispatch:

jobs:
  build-recovery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout TWRP manifest
        uses: actions/checkout@v3
        with:
          repository: minimal-manifest-twrp/platform_manifest_twrp_aosp
          path: twrp
          ref: twrp-12.1

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git-core gnupg flex bison build-essential \
            zip unzip curl repo \
            golang-go ninja-build clang lld \
            openjdk-11-jdk device-tree-compiler

      - name: Sync TWRP sources (1-job)
        working-directory: twrp
        run: |
          repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git \
            -b twrp-12.1 --depth=1
          repo sync -c --force-sync --no-tags -j1

      - name: Inject LG v600tm device tree
        run: |
          mkdir -p twrp/device/lge/v600tm
          cp -r device/lge/v600tm/devicetree/* twrp/device/lge/v600tm/

      - name: Generate TWRP makefiles
        working-directory: twrp/device/lge/v600tm
        run: |
          cat > AndroidProducts.mk << EOF
PRODUCT_MAKEFILES := \$(LOCAL_PATH)/device_lge_v600tm.mk
EOF
          cat > device_lge_v600tm.mk << EOF
PRODUCT_NAME := twrp_v600tm
PRODUCT_DEVICE := v600tm
PRODUCT_BRAND := lge
PRODUCT_MODEL := LGV600TM
PRODUCT_MANUFACTURER := LGE

\$(call inherit-product, vendor/twrp/config/common-twrp-device.mk)
EOF
          cat > BoardConfig.mk << EOF
BOARD_NAME := v600tm
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := cortex-a53
TARGET_CPU_VARIANT := cortex-a53
BOARD_PREBUILT_DTBO_IMAGE := device/lge/v600tm/prebuilt-dtb/v600tm.dtb
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x02000000
BOARD_SYSTEMIMAGE_PARTITION_SIZE   := 0x200000000
EOF

      - name: Debug: List build directory contents
        working-directory: twrp
        run: |
          ls -la
          ls -la build || true

      - name: Build only the recovery image
        working-directory: twrp
        shell: bash
        run: |
          if [ ! -f build/envsetup.sh ]; then
            echo "envsetup.sh not found!"; exit 1
          fi
          source build/envsetup.sh
          lunch twrp_v600tm-eng
          make -j1 recoveryimage

      - name: Upload recovery.img artifact
        uses: actions/upload-artifact@v3
        with:
          name: twrp_v600tm_recovery
          path: twrp/out/target/product/v600tm/recovery.img
